apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service-config
  namespace: execution-service
data:
  SERVER_PORT: "8080"
  SERVER_SERVLET_CONTEXT_PATH: "/api/execution-service"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_SHOW_SQL: "false"
  AWS_REGION: "us-east-1"
  SQS_EXECUTION_COMPLETED_QUEUE_URL: "__SQS_EXECUTION_COMPLETED_QUEUE_URL__"
  SQS_RESOURCE_UNAVAILABLE_QUEUE_URL: "__SQS_RESOURCE_UNAVAILABLE_QUEUE_URL__"
  SQS_BILLING_EVENTS_QUEUE: "__SQS_BILLING_EVENTS_QUEUE__"
  SQS_OS_EVENTS_QUEUE: "__SQS_OS_EVENTS_QUEUE__"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
