apiVersion: v1
kind: Secret
metadata:
  name: execution-service-secrets
  namespace: execution-service
type: Opaque
data:
  DB_URL: __DB_URL_B64__
  DB_USERNAME: __DB_USERNAME_B64__
  DB_PASSWORD: __DB_PASSWORD_B64__
  SQS_EXECUTION_EVENTS_QUEUE_URL: __SQS_EXECUTION_EVENTS_QUEUE_URL_B64__
